config/routes.rb
Rails.application.routes.draw do

  root to: 'movies#index'

  resources :movies do
    resources :reviews
    resources :favorites
  end

  resources :genres

  resources :users
  get 'signup', to: 'users#new'

  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>Made with ♥️ in Paris 🗼.  Copyright &copy; <%= Time.now.year %></p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "All Movies", movies_path %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Settings", edit_user_path(current_user) %>
        </li>
        <li>
          <%= link_to "Sign out", session_path, method: :delete, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign in", new_session_path, class: "button" %>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/header' %>

<div class="content">
  <%= render 'layouts/flash' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>